services:
  - type: web
    name: food-system-backend-no7d
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
