-- AddOrderSettings idempotente
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "acceptDelivery"     BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "acceptPickup"       BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "acceptDineIn"       BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "estimatedPrepTime"  INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "minimumOrderAmount" DECIMAL(10,2);
